const prefix = '/components/';

export default [
    { value: 'Color 色彩', path: `${prefix}color` },
    { value: 'Button 按钮', path: `${prefix}button` },
    { value: 'Icon 图标', path: `${prefix}icon` },
    { value: 'Card 卡片', path: `${prefix}card` },
    { value: 'Collapse 折叠面板', path: `${prefix}collapse` },
    { value: 'Divider 分割线', path: `${prefix}divider` },
    { value: 'PageHeader 页头', path: `${prefix}page-header` },
    { value: 'Tabs 标签页', path: `${prefix}tabs` },
    { value: 'Dropdown 下拉菜单', path: `${prefix}dropdown` },
    { value: 'Empty 空状态', path: `${prefix}empty` },
    { value: 'Jumbotron 巨幕', path: `${prefix}jumbotron` },
    { value: 'Breadcrumd 面包屑', path: `${prefix}breadcrumd` },
    { value: 'Badge 徽标数', path: `${prefix}badge` },
    { value: 'Steps 步骤条', path: `${prefix}steps` },
    { value: 'LoadingBar 加载中进度条', path: `${prefix}loading-bar` },
    { value: 'Radio 单选框', path: `${prefix}radio` },
    { value: 'Switch 开关', path: `${prefix}switch` },
    { value: 'Alert 警告', path: `${prefix}alert` },
    { value: 'Message 全局提示', path: `${prefix}message` },
    { value: 'Notice 通知提醒', path: `${prefix}notice` },
    { value: 'Modal 对话框', path: `${prefix}modal` },
    { value: '$Modal 轻量对话框', path: `${prefix}$modal` },
    { value: 'Drawer 抽屉', path: `${prefix}drawer` },
    { value: 'Tooltip 文字提示', path: `${prefix}tooltip` },
    { value: 'Poptip 气泡提示', path: `${prefix}poptip` },
    { value: 'Progress 进度条', path: `${prefix}progress` },
    { value: 'Result 结果', path: `${prefix}result` },
    { value: 'Skeleton 骨架屏', path: `${prefix}skeleton` },
    { value: 'Avatar 头像', path: `${prefix}avatar` },
    { value: 'Tag 标签', path: `${prefix}tag` },
    { value: 'Timeline 时间轴', path: `${prefix}timeline` },
    { value: 'Time 相对时间', path: `${prefix}time` },
    { value: 'BackTop 返回顶部', path: `${prefix}back-top` },
    { value: 'Spin 加载中', path: `${prefix}spin` }
];
