<template>
    <div class="markdown-code">
        <div class="code-write">
            <p style="font-size: 32px">Attributes</p>
            <h3><a name="card" class="md-header-anchor"></a><span>Card</span></h3>
            <figure>
                <table>
                    <thead>
                        <tr>
                            <th><span>属性</span></th>
                            <th><span>说明</span></th>
                            <th><span>默认值</span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><span>no-bodred</span></td>
                            <td><span>不显示边框，建议在灰色背景下使用</span></td>
                            <td><span>false</span></td>
                        </tr>
                        <tr>
                            <td><span>dis-hover</span></td>
                            <td><span>禁用鼠标悬停显示阴影</span></td>
                            <td><span>false</span></td>
                        </tr>
                        <tr>
                            <td><span>shadow</span></td>
                            <td><span>卡片阴影，建议在灰色背景下使用</span></td>
                            <td><span>false</span></td>
                        </tr>
                        <tr>
                            <td><span>title</span></td>
                            <td><span>卡片标题</span></td>
                            <td><span>-</span></td>
                        </tr>
                        <tr>
                            <td><span>extra</span></td>
                            <td><span>卡片额外操作的内容</span></td>
                            <td><span>-</span></td>
                        </tr>
                    </tbody>
                </table>
            </figure>
            <h3><a name="config--方法" class="md-header-anchor"></a><span>Config 方法</span></h3>
            <p>
                <span
                    >配置指定的组件，并提供一些必要的响应式更新DOM内容或其他操作的
                    API。（并不是每个组件都会有）</span
                >
            </p>
            <figure>
                <table>
                    <thead>
                        <tr>
                            <th><span>参数</span></th>
                            <th><span>说明</span></th>
                            <th><span>类型</span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><span>el</span></td>
                            <td><span>配置当前选定的 steps，必须是选择器名称或者元素名</span></td>
                            <td><span>String</span></td>
                        </tr>
                    </tbody>
                </table>
            </figure>
            <p><span>该方法返回以下2个 String 类型的属性：</span></p>
            <ul>
                <li><code>title</code></li>
                <li><code>extra</code></li>
            </ul>
            <figure>
                <table>
                    <thead>
                        <tr>
                            <th><span>返回值</span></th>
                            <th><span>说明</span></th>
                            <th><span>类型</span></th>
                            <th><span>默认值</span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><span>title</span></td>
                            <td><span>响应式设置卡片标题</span></td>
                            <td><span>String</span></td>
                            <td><span>-</span></td>
                        </tr>
                        <tr>
                            <td><span>extra</span></td>
                            <td><span>响应式设置卡片额外操作的内容</span></td>
                            <td><span>String</span></td>
                            <td><span>-</span></td>
                        </tr>
                    </tbody>
                </table>
            </figure>
        </div>
    </div>
</template>