import alertTest from './alert';
import avatarTest from './avatar';
import backtopTest from './back-top';
import badgeTest from './badge';
import breadcrumbTest from './breadcrumb';
import buttonTest from './button';
import cardTest from './card';
import carouselTest from './carousel';
import checkboxTest from './checkbox';
import collapseTest from './collapse';
import dividerTest from './divider';
import drawerTest from './drawer';
import dropdownTest from './dropdown';
import emptyTest from './empty';
import jumbotronTest from './jumbotron';
import loadingBarTest from './loading-bar';
import messageTest from './message';
import poptipTest from './poptip';
import modalTest from './modal';
import noticeTest from './notice';
import pageHeaderTest from './page-header';
import progressTest from './progress';
import radioTest from './radio';
import rateTest from './rate';
import resultTest from './result';
import skeletonTest from './skeleton';
import spinTest from './spin';
import stepsTest from './steps';
import switchTest from './switch';
import tabsTest from './tabs';
import tagTest from './tag';
import timeTest from './time';
import timelineTest from './timeline';
import tooltipTest from './tooltip';

import '../src/styles/index.less';

// alertTest();
// avatarTest();
// backtopTest();
// badgeTest();
// breadcrumbTest();
// buttonTest();
// cardTest();
// carouselTest();
// checkboxTest();
// collapseTest();
// dividerTest();
// drawerTest();
// dropdownTest();
// emptyTest();
// jumbotronTest();
// loadingBarTest();
// messageTest();
// modalTest();
// noticeTest();
// pageHeaderTest();
// poptipTest();
// progressTest();
// radioTest();
rateTest();
// resultTest();
// skeletonTest();
// stepsTest();
// spinTest();
// switchTest();
// tabsTest();
// tagTest();
// timeTest();
// timelineTest();
// tooltipTest();
