<template>
  <div class="">
    <h3><a name="button" class="md-header-anchor"></a><span>Button</span></h3>
    <figure>
      <table>
        <thead>
          <tr>
            <th><span>属性</span></th>
            <th><span>说明</span></th>
            <th><span>默认值</span></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span>loading</span></td>
            <td><span>设置按钮为加载中状态</span></td>
            <td><span>false</span></td>
          </tr>
          <tr>
            <td><span>disabled</span></td>
            <td><span>设置按钮为禁用状态</span></td>
            <td><span>false</span></td>
          </tr>
          <tr>
            <td><span>icon</span></td>
            <td><span>设置按钮的图标类型</span></td>
            <td><span>-</span></td>
          </tr>
        </tbody>
      </table>
    </figure>
    <h3><a name="config--方法" class="md-header-anchor"></a><span>Config 方法</span></h3>
    <p>
      <span
        >配置指定的组件，并提供一些必要的响应式更新DOM内容或其他操作的
        API。（并不是每个组件都会有）</span
      >
    </p>
    <figure>
      <table>
        <thead>
          <tr>
            <th><span>参数</span></th>
            <th><span>说明</span></th>
            <th><span>类型</span></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span>el</span></td>
            <td><span>配置当前选定的 button，必须是选择器名称或者元素名</span></td>
            <td><span>String</span></td>
          </tr>
        </tbody>
      </table>
    </figure>
    <p><span>该方法返回以下值：</span></p>
    <ul>
      <li><code>loading</code></li>
    </ul>
    <figure>
      <table>
        <thead>
          <tr>
            <th><span>返回值</span></th>
            <th><span>说明</span></th>
            <th><span>类型</span></th>
            <th><span>默认值</span></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span>loading</span></td>
            <td><span>响应式设置设置按钮为加载中状态</span></td>
            <td><span>Boolean</span></td>
            <td><span>false</span></td>
          </tr>
        </tbody>
      </table>
    </figure>
  </div>
</template>
