import {
    ElContainer,
    ElHeader,
    ElMain,
    ElAside,
    ElFooter,
    ElRow,
    ElCol,
    ElButton,
    ElMenu,
    ElMenuItemGroup,
    ElMenuItem,
    ElIcon,
    ElAutocomplete,
    ElDivider,
    ElTimeline,
    ElTimelineItem,
    ElCard,
    ElCollapse,
    ElCollapseItem,
    ElInput
} from 'element-plus';

export default [
    ElContainer,
    ElHeader,
    ElMain,
    ElAside,
    ElFooter,
    ElRow,
    ElCol,
    ElButton,
    ElMenu,
    ElMenuItemGroup,
    ElMenuItem,
    ElIcon,
    ElAutocomplete,
    ElDivider,
    ElTimeline,
    ElTimelineItem,
    ElCard,
    ElCollapse,
    ElCollapseItem,
    ElInput
];
